### ISSUE TITLE
Perform manual test with PyKMIP.

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill-kmip-protocol#14]

**Comment by ximon18** [comment]
```bash
$ git describe --always
afb314d

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ cat /etc/pykmip/server.conf
[server]
database_path=/etc/pykmip/pykmip.database
hostname=127.0.0.1
port=5696
certificate_path=/etc/ssl/certs/selfsigned.crt
key_path=/etc/ssl/private/selfsigned.key
ca_path=/etc/ssl/certs/selfsigned.crt
auth_suite=TLS1.2
policy_path=/usr/local/PyKMIP/examples/
enable_tls_client_auth=False
logging_level=INFO

$ cargo run --example cli-tool -- -c /etc/ssl/certs/selfsigned.crt -k /etc/ssl/private/selfsigned.key 2>&1 | fold -w 120
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/cli-tool -c /etc/ssl/certs/selfsigned.crt -k /etc/ssl/private/selfsigned.key`
2021-08-16T10:52:15+02:00 - INFO - Querying server properties..
2021-08-16T10:52:15+02:00 - INFO - QueryResponsePayload { operations: Some([Create, CreateKeyPair, Register, DeriveKey, 
Locate, Get, GetAttributes, GetAttributeList, Activate, Revoke, Destroy, Query]), object_types: None, vendor_identificat
ion: Some("PyKMIP 0.11.0dev1 Software Server"), server_information: None }
2021-08-16T10:52:15+02:00 - INFO - Created key pair:
2021-08-16T10:52:15+02:00 - INFO -   Private key ID: 82
2021-08-16T10:52:15+02:00 - INFO -   Public key ID : 81
2021-08-16T10:52:15+02:00 - INFO - Activating private key..
2021-08-16T10:52:15+02:00 - INFO - Signing with private key..
2021-08-16T10:52:15+02:00 - INFO - 725FC769D25FC281D8BF89DFFEFF6662F4F48654F2857898134782FC6993935EB81A9EFB89ECB14345ECC
2980A9EA7D172103B2012BCCF213CB142130C07AFCB6131BF67D79A02B1CA062803364C1EFECFD5DADED405FCDAB3B8E435AA43B797545375C5BB1EF
84E0DDC00F6F5E66B63669CD6BBE5F678786A837BCE72D8A57E1F6DAEDC606CBDB9642D66318691284B94A12BAD9006CD537D5E1DA91EE2EB94FFD81
46B0961E23FC519EDE70983C42489A82F89ADB66989F6EB1E98DDEF86F7AECF18C8123D4F7A76F6DCEF45AFA40DADACCB25091C223414D7A40E41E55
BA3DC56D5DA5A3327D283BC178453F6F15ECC158027D20A21AEFC139C73DBAB2835
2021-08-16T10:52:15+02:00 - INFO - Revoking private key..
2021-08-16T10:52:15+02:00 - INFO - Deleting public key..
2021-08-16T10:52:15+02:00 - INFO - Deleting private key..
2021-08-16T10:52:15+02:00 - INFO - Requesting 32 random bytes..
2021-08-16T10:52:15+02:00 - ERROR - Request for 32 random bytes failed
```

The failure to generate random bytes using the `RNG Retrieve` operation is expected as the result of the `Query` operation did not include `RNG Retrieve` in the set of operations supporrted by the PyKMIP server. The PyKMIP server log confirms this:

```bash
cat /var/log/pykmip/server.log
2021-08-16 10:52:13,220 - kmip.server.config - INFO - Loading server configuration settings from: /etc/pykmip/server.conf
2021-08-16 10:52:13,232 - kmip.server.monitor - INFO - Starting up the operation policy file monitor.
2021-08-16 10:52:13,239 - kmip.server - INFO - Starting server socket handler.
2021-08-16 10:52:13,241 - kmip.server - INFO - Server successfully bound socket handler to 127.0.0.1:5696
2021-08-16 10:52:13,241 - kmip.server - INFO - Starting connection service...
2021-08-16 10:52:14,234 - kmip.server.monitor - INFO - Loading policies for file: /usr/local/PyKMIP/examples/legacy_policy.json
2021-08-16 10:52:14,237 - kmip.server.monitor - INFO - Loading policy: example
2021-08-16 10:52:14,239 - kmip.server.monitor - INFO - Loading policies for file: /usr/local/PyKMIP/examples/policy.json
2021-08-16 10:52:14,240 - kmip.server.monitor - INFO - Loading policy: example
2021-08-16 10:52:15,250 - kmip.server - INFO - Receiving incoming connection from: 127.0.0.1:33916
2021-08-16 10:52:15,250 - kmip.server - INFO - Dedicating session 00000001 to 127.0.0.1:33916
2021-08-16 10:52:15,251 - kmip.server.session.00000001 - INFO - Starting session: 00000001
2021-08-16 10:52:15,282 - kmip.server.session.00000001 - INFO - Session client identity: localhost
2021-08-16 10:52:15,283 - kmip.server.engine - INFO - Received request at time: 2021-08-16 08:52:15
2021-08-16 10:52:15,283 - kmip.server.engine - INFO - Processing operation: Query
2021-08-16 10:52:15,287 - kmip.server.session.00000001 - INFO - Session client identity: localhost
2021-08-16 10:52:15,288 - kmip.server.engine - INFO - Received request at time: 2021-08-16 08:52:15
2021-08-16 10:52:15,288 - kmip.server.engine - INFO - Processing operation: CreateKeyPair
2021-08-16 10:52:15,288 - kmip.server.engine.cryptography - INFO - Generating an RSA key pair with length: 2048, and public_exponent: 65537
2021-08-16 10:52:15,491 - kmip.server.engine - INFO - Created a PublicKey with ID: 81
2021-08-16 10:52:15,494 - kmip.server.engine - INFO - Created a PrivateKey with ID: 82
2021-08-16 10:52:15,496 - kmip.server.session.00000001 - INFO - Session client identity: localhost
2021-08-16 10:52:15,496 - kmip.server.engine - INFO - Received request at time: 2021-08-16 08:52:15
2021-08-16 10:52:15,496 - kmip.server.engine - INFO - Processing operation: Activate
2021-08-16 10:52:15,512 - kmip.server.session.00000001 - INFO - Session client identity: localhost
2021-08-16 10:52:15,512 - kmip.server.engine - INFO - Received request at time: 2021-08-16 08:52:15
2021-08-16 10:52:15,512 - kmip.server.engine - INFO - Processing operation: Sign
2021-08-16 10:52:15,522 - kmip.server.session.00000001 - INFO - Session client identity: localhost
2021-08-16 10:52:15,523 - kmip.server.engine - INFO - Received request at time: 2021-08-16 08:52:15
2021-08-16 10:52:15,523 - kmip.server.engine - INFO - Processing operation: Revoke
2021-08-16 10:52:15,536 - kmip.server.session.00000001 - INFO - Session client identity: localhost
2021-08-16 10:52:15,536 - kmip.server.engine - INFO - Received request at time: 2021-08-16 08:52:15
2021-08-16 10:52:15,537 - kmip.server.engine - INFO - Processing operation: Destroy
2021-08-16 10:52:15,545 - kmip.server.engine - INFO - Destroying an object with ID: 81
2021-08-16 10:52:15,555 - kmip.server.session.00000001 - INFO - Session client identity: localhost
2021-08-16 10:52:15,556 - kmip.server.engine - INFO - Received request at time: 2021-08-16 08:52:15
2021-08-16 10:52:15,556 - kmip.server.engine - INFO - Processing operation: Destroy
2021-08-16 10:52:15,559 - kmip.server.engine - INFO - Destroying an object with ID: 82
2021-08-16 10:52:15,568 - kmip.server.session.00000001 - WARNING - Failure parsing request message.
2021-08-16 10:52:15,568 - kmip.server.session.00000001 - ERROR - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/PyKMIP-0.11.0.dev1-py3.6.egg/kmip/services/server/session.py", line 167, in _handle_message_loop
    request.read(request_data, kmip_version=kmip_version)
  File "/usr/local/lib/python3.6/dist-packages/PyKMIP-0.11.0.dev1-py3.6.egg/kmip/core/messages/messages.py", line 485, in read
    batch_item.read(istream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.6/dist-packages/PyKMIP-0.11.0.dev1-py3.6.egg/kmip/core/messages/messages.py", line 308, in read
    self.operation.value)
  File "/usr/local/lib/python3.6/dist-packages/PyKMIP-0.11.0.dev1-py3.6.egg/kmip/core/factories/payloads/__init__.py", line 98, in create
    return self._create_rng_retrieve_payload()
  File "/usr/local/lib/python3.6/dist-packages/PyKMIP-0.11.0.dev1-py3.6.egg/kmip/core/factories/payloads/__init__.py", line 222, in _create_rng_retrieve_payload
    raise NotImplementedError()
NotImplementedError
2021-08-16 10:52:15,570 - kmip.server.session.00000001 - INFO - Stopping session: 00000001
2021-08-16 10:52:17,199 - kmip.server - WARNING - Interrupting connection service.
2021-08-16 10:52:17,200 - kmip.server - INFO - Stopping connection service.
2021-08-16 10:52:17,200 - kmip.server - INFO - Cleaning up remaining connection threads.
2021-08-16 10:52:17,200 - kmip.server - INFO - Shutting down server socket handler.
```
